interface port {
  variant port-error {
    not-found,
    error(string),
  }

  record port-data {
    data: list<u8>,
    wfid: string,
    wfstate: string,
    wfhist: list<string>
  }

  resource ports {
    constructor();
    call-port: func(port-name: string, data: port-data) -> result<port-data, port-error>;
  }
}