// Generated by `wit-bindgen` 0.34.0. DO NOT EDIT!
#include "sdk.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `taho:sdk/api`

__attribute__((__import_module__("taho:sdk/api"), __import_name__("[constructor]model")))
extern int32_t __wasm_import_taho_sdk_api_constructor_model(void);

__attribute__((__import_module__("taho:sdk/api"), __import_name__("[method]model.invoke-port")))
extern void __wasm_import_taho_sdk_api_method_model_invoke_port(int32_t, uint8_t *, size_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("taho:sdk/api"), __import_name__("import-model")))
extern int32_t __wasm_import_taho_sdk_api_import_model(uint8_t *, size_t, uint8_t *, size_t);

__attribute__((__import_module__("taho:sdk/api"), __import_name__("get-model-spec")))
extern void __wasm_import_taho_sdk_api_get_model_spec(uint8_t *);

// Exported Functions from `taho:sdk/ports`


__attribute__((__weak__, __export_name__("cabi_post_taho:sdk/ports#[method]callbacks.invoke-port")))
void __wasm_export_exports_taho_sdk_ports_method_callbacks_invoke_port_post_return(uint8_t * arg0) {
  switch ((int32_t) (int32_t) *((uint8_t*) (arg0 + 0))) {
    case 0: {
      break;
    }
    case 1: {
      size_t len = *((size_t*) (arg0 + 8));
      if (len > 0) {
        uint8_t *ptr = *((uint8_t **) (arg0 + 4));
        for (size_t i = 0; i < len; i++) {
          uint8_t *base = ptr + i * 1;
          (void) base;
        }
        free(ptr);
      }
      break;
    }
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void taho_sdk_api_error_free(taho_sdk_api_error_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 0: {
      sdk_string_free(&ptr->val.known_error);
      break;
    }
    case 1: {
      sdk_string_free(&ptr->val.unknown_error);
      break;
    }
  }
}

void taho_sdk_api_model_spec_free(taho_sdk_api_model_spec_t *ptr) {
  sdk_string_free(&ptr->model_name);
  sdk_string_free(&ptr->domain_name);
}

__attribute__((__import_module__("taho:sdk/api"), __import_name__("[resource-drop]model")))
extern void __wasm_import_taho_sdk_api_model_drop(int32_t handle);

void taho_sdk_api_model_drop_own(taho_sdk_api_own_model_t handle) {
  __wasm_import_taho_sdk_api_model_drop(handle.__handle);
}

taho_sdk_api_borrow_model_t taho_sdk_api_borrow_model(taho_sdk_api_own_model_t arg) {
  return (taho_sdk_api_borrow_model_t) { arg.__handle };
}

void sdk_list_u8_free(sdk_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void taho_sdk_api_result_list_u8_error_free(taho_sdk_api_result_list_u8_error_t *ptr) {
  if (!ptr->is_err) {
    sdk_list_u8_free(&ptr->val.ok);
  } else {
    taho_sdk_api_error_free(&ptr->val.err);
  }
}

__attribute__((__import_module__("[export]taho:sdk/ports"), __import_name__("[resource-drop]callbacks")))
extern void __wasm_import_exports_taho_sdk_ports_callbacks_drop(int32_t handle);

void exports_taho_sdk_ports_callbacks_drop_own(exports_taho_sdk_ports_own_callbacks_t handle) {
  __wasm_import_exports_taho_sdk_ports_callbacks_drop(handle.__handle);
}

__attribute__(( __import_module__("[export]taho:sdk/ports"), __import_name__("[resource-new]callbacks")))
extern int32_t __wasm_import_exports_taho_sdk_ports_callbacks_new(int32_t);

__attribute__((__import_module__("[export]taho:sdk/ports"), __import_name__("[resource-rep]callbacks")))
extern int32_t __wasm_import_exports_taho_sdk_ports_callbacks_rep(int32_t);

exports_taho_sdk_ports_own_callbacks_t exports_taho_sdk_ports_callbacks_new(exports_taho_sdk_ports_callbacks_t *rep) {
  return (exports_taho_sdk_ports_own_callbacks_t) { __wasm_import_exports_taho_sdk_ports_callbacks_new((int32_t) rep) };
}

exports_taho_sdk_ports_callbacks_t* exports_taho_sdk_ports_callbacks_rep(exports_taho_sdk_ports_own_callbacks_t handle) {
  return (exports_taho_sdk_ports_callbacks_t*) __wasm_import_exports_taho_sdk_ports_callbacks_rep(handle.__handle);
}

__attribute__((__export_name__("taho:sdk/ports#[dtor]callbacks")))
void __wasm_export_exports_taho_sdk_ports_callbacks_dtor(exports_taho_sdk_ports_callbacks_t* arg) {
  exports_taho_sdk_ports_callbacks_destructor(arg);
}

void sdk_option_list_u8_free(sdk_option_list_u8_t *ptr) {
  if (ptr->is_some) {
  }
}

void sdk_string_set(sdk_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void sdk_string_dup(sdk_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void sdk_string_free(sdk_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[12];

taho_sdk_api_own_model_t taho_sdk_api_constructor_model(void) {
  int32_t ret = __wasm_import_taho_sdk_api_constructor_model();
  return (taho_sdk_api_own_model_t) { ret };
}

bool taho_sdk_api_method_model_invoke_port(taho_sdk_api_borrow_model_t self, sdk_string_t *port_name, sdk_list_u8_t *data, sdk_list_u8_t *ret, taho_sdk_api_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_taho_sdk_api_method_model_invoke_port((self).__handle, (uint8_t *) (*port_name).ptr, (*port_name).len, (uint8_t *) (*data).ptr, (*data).len, ptr);
  taho_sdk_api_result_list_u8_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (sdk_list_u8_t) { (uint8_t*)(*((uint8_t **) (ptr + 4))), (*((size_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      taho_sdk_api_error_t variant;
      variant.tag = (int32_t) *((uint8_t*) (ptr + 4));
      switch ((int32_t) variant.tag) {
        case 0: {
          variant.val.known_error = (sdk_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
        case 1: {
          variant.val.unknown_error = (sdk_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) };
          break;
        }
      }

      result.val.err = variant;
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

taho_sdk_api_own_model_t taho_sdk_api_import_model(sdk_string_t *name, sdk_string_t *url) {
  int32_t ret = __wasm_import_taho_sdk_api_import_model((uint8_t *) (*name).ptr, (*name).len, (uint8_t *) (*url).ptr, (*url).len);
  return (taho_sdk_api_own_model_t) { ret };
}

void taho_sdk_api_get_model_spec(taho_sdk_api_model_spec_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[16];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_taho_sdk_api_get_model_spec(ptr);
  *ret = (taho_sdk_api_model_spec_t) {
    (sdk_string_t) (sdk_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + 4))) },
    (sdk_string_t) (sdk_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 8))), (*((size_t*) (ptr + 12))) },
  };
}

__attribute__((__export_name__("taho:sdk/ports#[constructor]callbacks")))
int32_t __wasm_export_exports_taho_sdk_ports_constructor_callbacks(void) {
  exports_taho_sdk_ports_own_callbacks_t ret = exports_taho_sdk_ports_constructor_callbacks();
  return (ret).__handle;
}

__attribute__((__export_name__("taho:sdk/ports#[method]callbacks.invoke-port")))
uint8_t * __wasm_export_exports_taho_sdk_ports_method_callbacks_invoke_port(uint8_t * arg, uint8_t * arg0, size_t arg1, uint8_t * arg2, size_t arg3) {
  sdk_string_t arg4 = (sdk_string_t) { (uint8_t*)(arg0), (arg1) };
  sdk_list_u8_t arg5 = (sdk_list_u8_t) { (uint8_t*)(arg2), (arg3) };
  sdk_list_u8_t val;
  bool ret = exports_taho_sdk_ports_method_callbacks_invoke_port(((exports_taho_sdk_ports_callbacks_t*) arg), &arg4, &arg5, &val);

  sdk_option_list_u8_t ret6;
  ret6.is_some = ret;
  ret6.val = val;
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  if ((ret6).is_some) {
    const sdk_list_u8_t *payload7 = &(ret6).val;
    *((int8_t*)(ptr + 0)) = 1;
    *((size_t*)(ptr + 8)) = (*payload7).len;
    *((uint8_t **)(ptr + 4)) = (uint8_t *) (*payload7).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_sdk(void);
void __component_type_object_force_link_sdk_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_sdk();
}
