// Generated by `wit-bindgen` 0.34.0. DO NOT EDIT!
#ifndef __BINDINGS_SDK_H
#define __BINDINGS_SDK_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct sdk_string_t {
  uint8_t*ptr;
  size_t len;
} sdk_string_t;

typedef struct taho_sdk_api_error_t {
  uint8_t tag;
  union {
    sdk_string_t     known_error;
    sdk_string_t     unknown_error;
  } val;
} taho_sdk_api_error_t;

#define taho_SDK_API_ERROR_KNOWN_ERROR 0
#define taho_SDK_API_ERROR_UNKNOWN_ERROR 1

typedef struct taho_sdk_api_model_spec_t {
  sdk_string_t   model_name;
  sdk_string_t   domain_name;
} taho_sdk_api_model_spec_t;

typedef struct taho_sdk_api_own_model_t {
  int32_t __handle;
} taho_sdk_api_own_model_t;

typedef struct taho_sdk_api_borrow_model_t {
  int32_t __handle;
} taho_sdk_api_borrow_model_t;

typedef struct {
  uint8_t *ptr;
  size_t len;
} sdk_list_u8_t;

typedef struct {
  bool is_err;
  union {
    sdk_list_u8_t ok;
    taho_sdk_api_error_t err;
  } val;
} taho_sdk_api_result_list_u8_error_t;

typedef struct exports_taho_sdk_ports_own_callbacks_t {
  int32_t __handle;
} exports_taho_sdk_ports_own_callbacks_t;

typedef struct exports_taho_sdk_ports_callbacks_t exports_taho_sdk_ports_callbacks_t;

typedef exports_taho_sdk_ports_callbacks_t* exports_taho_sdk_ports_borrow_callbacks_t;

typedef struct {
  bool is_some;
  sdk_list_u8_t val;
} sdk_option_list_u8_t;

// Imported Functions from `taho:sdk/api`
extern taho_sdk_api_own_model_t taho_sdk_api_constructor_model(void);
extern bool taho_sdk_api_method_model_invoke_port(taho_sdk_api_borrow_model_t self, sdk_string_t *port_name, sdk_list_u8_t *data, sdk_list_u8_t *ret, taho_sdk_api_error_t *err);
extern taho_sdk_api_own_model_t taho_sdk_api_import_model(sdk_string_t *name, sdk_string_t *url);
extern void taho_sdk_api_get_model_spec(taho_sdk_api_model_spec_t *ret);

// Exported Functions from `taho:sdk/ports`
exports_taho_sdk_ports_own_callbacks_t exports_taho_sdk_ports_constructor_callbacks(void);
bool exports_taho_sdk_ports_method_callbacks_invoke_port(exports_taho_sdk_ports_borrow_callbacks_t self, sdk_string_t *port_name, sdk_list_u8_t *data, sdk_list_u8_t *ret);

// Helper Functions

void taho_sdk_api_error_free(taho_sdk_api_error_t *ptr);

void taho_sdk_api_model_spec_free(taho_sdk_api_model_spec_t *ptr);

extern void taho_sdk_api_model_drop_own(taho_sdk_api_own_model_t handle);

extern taho_sdk_api_borrow_model_t taho_sdk_api_borrow_model(taho_sdk_api_own_model_t handle);

void sdk_list_u8_free(sdk_list_u8_t *ptr);

void taho_sdk_api_result_list_u8_error_free(taho_sdk_api_result_list_u8_error_t *ptr);

extern void exports_taho_sdk_ports_callbacks_drop_own(exports_taho_sdk_ports_own_callbacks_t handle);

extern exports_taho_sdk_ports_own_callbacks_t exports_taho_sdk_ports_callbacks_new(exports_taho_sdk_ports_callbacks_t *rep);
extern exports_taho_sdk_ports_callbacks_t* exports_taho_sdk_ports_callbacks_rep(exports_taho_sdk_ports_own_callbacks_t handle);
void exports_taho_sdk_ports_callbacks_destructor(exports_taho_sdk_ports_callbacks_t *rep);

void sdk_option_list_u8_free(sdk_option_list_u8_t *ptr);

// Transfers ownership of `s` into the string `ret`
void sdk_string_set(sdk_string_t *ret, const char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void sdk_string_dup(sdk_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void sdk_string_free(sdk_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
